### ISSUE TITLE
Set WebTorrent as the default handler for .torrent files and magnet links

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-app#77]
Let's add a button to the Preferences Pane #62 for enabling this for magnet links. Like with lots of other things, I think Transmission gets this UI and wording right:

<img width="344" alt="screen shot 2016-03-07 at 6 24 27 pm" src="https://cloud.githubusercontent.com/assets/121766/13590080/edcc4cd2-e491-11e5-9dbe-54625de8b03c.png">

For .torrent files, I think we just register with the OS that our application can open .torrent files and leave it up to the OS and user to configure WebTorrent as their default.

## Tasks 

- [x] OS X: Handle .torrent files
- [x] OS X: Handle magnet links
- [x] Windows: Handle .torrent files
- [x] Windows: Handle magnet links
- [x] Linux: Handle .torrent files
- [x] Linux: Handle magnet links

**Comment by feross** [comment]
Ubuntu protocol handler intsructions: https://askubuntu.com/questions/514125/url-protocol-handlers-in-basic-ubuntu-desktop

**Comment by feross** [comment]
Okay, since I just got Windows magnet links working, going to just do .torrent file handling too.

**Comment by feross** [comment]
This is done! Whew, that was a lot of hacky, platform-specific code!
